### ISSUE TITLE
Use post CSS to removed unused classes

### ISSUE THREAD

**Issue by ninest** [ninest/unique-code#1]
Use with Tailwind (and auto-prefixer)

**Comment by mining016** [comment]
any update on this?

**Comment by ninest** [comment]
Thanks for the reminder, @mining016!

Relevant documentation:
- https://v1.tailwindcss.com/docs/controlling-file-size#purge-css-options
- https://v1.tailwindcss.com/docs/upcoming-changes#purge-layers-by-default

In the latest commit, the output CSS file has reduced from 1.6 mb to 6.4 kb!

Note that I haven't yet upgraded to Tailwind 2.
